### ISSUE TITLE
1.0.1 published package is empty

### ISSUE THREAD

**Issue by SBoudrias** [dielduarte/animate-css-styled-components#12]
The latest version published on npm is completely empty apart from a `package.json` file.

Maybe something went wrong with the prepublish build process?

**Comment by dielduarte** [comment]
Wow! @SBoudrias thanks for your help! I was testing github actions to publish directly to npm, I guess that something went wrong. I'll fix that asap!

**Comment by dielduarte** [comment]
I've just forced 1.0.2 version, and checked if everything went well!

Thanks!
