### ISSUE TITLE
How to use with reactstrap modal

### ISSUE THREAD

**Issue by ehdgua01** [dielduarte/animate-css-styled-components#15]
reactstrap: 8.0.0
styled-components: 4.2.0
animate-css-styled-components: 1.0.2

i use Modal component under Animate component but that is not working
How shall I do it?

**Comment by ehdgua01** [comment]
How is it to set animation target?

**Comment by dielduarte** [comment]
hey! could you provide an example? hosted in somewhere or repository that I can see the actual code. thanks!

**Comment by ehdgua01** [comment]
how about this?

<Bounce duration="1s" delay="0.1s" targetClassName="modal-content">
    <Modal />
</Bounce>

**Comment by dielduarte** [comment]
my guess is that I'm not passing external props to the animate component as you are using `targetClassName` and that prop aren't propagated. I'll do some tests and if is that the problem it's easy to solve.

**Comment by ehdgua01** [comment]
If it solve, Can you let me know?
thank you.
