### ISSUE TITLE
Published version on npm is not built

### ISSUE THREAD

**Issue by mshick** [dielduarte/animate-css-styled-components#2]
I just installed to give this a test run and noticed your published lib lacks a `lib` directory.

**Comment by dielduarte** [comment]
hey @mshick, I'll verify this and report to you.  thanks for your feedback!

**Comment by dielduarte** [comment]
@mshick you could test again? I publish 0.0.13 version fixed this.

**Comment by mshick** [comment]
Cool, working now. Thanks! 

I really appreciate your project.

**Comment by dielduarte** [comment]
@mshick Thanks for you help, let me know if you have other issue or PR, I'm open for suggestions. :)
