### ISSUE TITLE
Export BaseAnimation component?

### ISSUE THREAD

**Issue by mshick** [dielduarte/animate-css-styled-components#3]
I think this would be useful.

My use case: I'm looking to implement an element that slides up from 50% to 0. I was going to make a simple custom animation for this, very similar to your SlideUp animation.

**Comment by dielduarte** [comment]
hi @mshick, 

it's a great idea! and it's very simple to do.

**Comment by dielduarte** [comment]
@mshick thanks for you help! I implemented this on version 0.0.14. Update your lib and create your custom animations. see the documentation for how to make this here: https://github.com/dielduarte/animate-css-styled-components#how-to-create-custom-styled-animations
