### ISSUE TITLE
Latest version 0.0.18 doesn't work

### ISSUE THREAD

**Issue by ingridoberbuchler** [dielduarte/animate-css-styled-components#7]
@dielduarte Please update all dependencies.
Using `npm install animate-css-styled-components` error: _animate-css-styled-components Can't resolve 'stylis'_

Latest working version is 0.0.17

**Comment by dielduarte** [comment]
@ingridoberbuchler thanks for your report, I'm looking and will fix this today!

**Comment by dielduarte** [comment]
@ingridoberbuchler  Hi ingrid,  I just tested the version 0.0.18 in two projects that I'm  working and I did not have this problem, could you remove and install again? I'll close this issue but if problem come back, please open other issue and let me know more ok? thanks for your help.
